services:
  backend:
    ports:
      - 8081:8081

  frontend:
    ports:
      - 5173:5173

  db:
    expose:
      - 5432

  prometheus:
    ports:
      - 9090:9090

  grafana:
    ports:
      - 3000:3000
