---

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    restart: unless-stopped
    env_file: ./docker/caddy/.env
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 2019
    depends_on:
      - backend
      - frontend
      - grafana
    networks:
      - proxy

  backend:
    <<: &backend
      image: "ghcr.io/wemaketutor/backend:latest"
      restart: unless-stopped
    command: runner
    networks:
      - proxy
    expose:
      - 8081

  frontend:
    image: "ghcr.io/wemaketutor/frontend:latest"
    restart: unless-stopped
    command: runner
    networks:
      - proxy
    expose:
      - 5173

  node_exporter:
    image: "prom/node-exporter:v1.8.2"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
      - --collector.processes
      - --collector.systemd
    expose:
      - 9100
    networks:
      - monitoring

  grafana:
    networks:
      - proxy
    expose:
      - 3000

  prometheus:
    depends_on:
      - node_exporter
    networks:
      - proxy
    expose:
      - 9090

  db:
    expose:
      - 5432

networks:
  proxy:

volumes:
  django-media:
  django-locale:
  caddy-config:
  caddy-data:
