---

services:
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    restart: unless-stopped
    env_file: ./docker/caddy/.env
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - grafana
      - prometheus
    networks:
      - proxy

  backend:
    <<: &backend
      image: "ghcr.io/wemaketutor/backend:latest"
      restart: unless-stopped
    command: runner
    networks:
      - proxy
    expose:
      - 8081

  frontend:
    image: "ghcr.io/wemaketutor/frontend:latest"
    restart: unless-stopped
    command: runner
    networks:
      - proxy
    expose:
      - 8081

  grafana:
    networks:
      - proxy
    expose:
      - 3000

  prometheus:
    networks:
      - proxy
    expose:
      - 9090

  db:
    expose:
      - 5432

networks:
  proxy:

volumes:
  django-media:
  django-locale:
  caddy-config:
  caddy-data:
