scrape_configs:
  - job_name: 'backend_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8081']

  - job_name: 'caddy_monitoring'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['caddy:2019']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
