name: Deploy

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip deploy]')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /srv/platform
            docker compose -f ./docker-compose.yml -f ./docker/docker-compose.prod.yml pull
            docker compose -f ./docker-compose.yml -f ./docker/docker-compose.prod.yml up -d
