name: Build Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip push]')"

    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/frontend/Dockerfile
          tags: ghcr.io/wemaketutor/frontend:latest

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/backend/Dockerfile
          tags: ghcr.io/wemaketutor/backend:latest
