name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git Submodule Pull
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/frontend/Dockerfile
          tags: wemaketutor/frontend:latest

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/backend/Dockerfile
          tags: wemaketutor/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /srv/platform
            docker compose -f ./docker-compose.yml -f ./docker/docker-compose.prod.yml pull
            docker compose -f ./docker-compose.yml -f ./docker/docker-compose.prod.yml up -d
